M48
; DRILL file {KiCad 9.0.2} date 2025-07-19T17:43:14+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-19T17:43:14+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.500
%
G90
G05
T1
X112.0Y-40.0
X127.0Y-51.0
T2
X117.96Y-57.0
X120.5Y-57.0
X123.04Y-57.0
T3
X126.5Y-39.0
X146.99Y-39.0
M30
